// @flow
export const FETCH_CONTRIBUTORS_REQUEST = "FETCH_CONTRIBUTORS_REQUEST";
export type FETCH_CONTRIBUTORS_REQUEST_TYPE = "FETCH_CONTRIBUTORS_REQUEST";
export const FETCH_CONTRIBUTORS_SUCCESS = "FETCH_CONTRIBUTORS_SUCCESS";
export type FETCH_CONTRIBUTORS_SUCCESS_TYPE = "FETCH_CONTRIBUTORS_SUCCESS";
export const FETCH_CONTRIBUTORS_FAILURE = "FETCH_CONTRIBUTORS_FAILURE";
export type FETCH_CONTRIBUTORS_FAILURE_TYPE = "FETCH_CONTRIBUTORS_FAILURE";
